module.exports = {
  NO_PERMISSSION: { errorCode: 0, errorMsg: "没有权限访问" },
  NO_PARAMS: { errorCode: 1, errorMsg: "缺少请求参数" },
  GET_DAILY_TASK_FAIL: { errorCode: 101, errorMsg: "获取每日任务失败" },
  APPLY_TASK_FAIL: { errorCode: 201, errorMsg: "申请任务失败" },
  CHECK_TASK_FAIL: { errorCode: 202, errorMsg: "审核任务失败" },
  GET_PENDING_CHECK_TASK_FAIL: { errorCode: 203, errorMsg: "获取待审核的任务列表失败" },
  GET_TASK_DETAILS_FAIL: { errorCode: 204, errorMsg: "获取任务详情失败" },
  FINIASH_TASK_FAIL: { errorCode: 301, errorMsg: "完成任务失败" },
  GET_TASK_LIST_FAIL: { errorCode: 401, errorMsg: "获取任务列表失败" },
  GET_AWARD_LIST_FAIL: { errorCode: 402, errorMsg: "获取兑换奖励失败" },
  APPLY_AWARD_FAIL: { errorCode: 501, errorMsg: "奖励新增申请失败" },
  CHECK_AWARD_FAIL: { errorCode: 502, errorMsg: "审核奖励失败" },
  GET_PENDING_CHECK_AWARD_FAIL: { errorCode: 503, errorMsg: "获取待审核的奖励列表失败" },
  GET_AWARD_DETAILS_FAIL: { errorCode: 504, errorMsg: "获取奖励详情失败" },
  GET_SCORE_DETAILS_FAIL: { errorCode: 601, errorMsg: "查询积分明细失败" },
  APPLY_EXCHANGE_FAIL: { errorCode: 701, errorMsg: "申请兑换失败" },
  GET_EXCHANGE_LIST_FAIL: { errorCode: 702, errorMsg: "获取兑换列表失败" },
  CONFIRM_EXCHANGE_FAIL: { errorCode: 703, errorMsg: "确认兑换失败" },
  GET_EXCHANGE_DETAILS_FAIL: { errorCode: 704, errorMsg: "获取兑换详情失败" },
  GET_NOW_SCORE_FAIL: { errorCode: 801, errorMsg: "获取当前总积分失败" },
  DELETE_TASK_FAIL: { errorCode: 901, errorMsg: "删除任务失败" },
  DELETE_AWARD_FAIL: { errorCode: 902, errorMsg: "删除奖励失败" },
};
